version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing kubectl...
  build:
    commands:
      - echo Deployment started on `date`
      - echo Rolling Kubernetes deployment...
      - env
      - kubectl version 
  post_build:
    commands:
      - echo Deployment finished on `date`
reports:
  jest_reports:
    files:
      - simple-http-api-results.xml
    file-format: JUNITXML
    base-directory: test-results/jest
